# Generated by Django 3.0 on 2021-01-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200504_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Certified_In',
            field=models.CharField(blank=True, default='', help_text='You Can Add Your Certifications Here..', max_length=39),
        ),
        migrations.AddField(
            model_name='profile',
            name='Country',
            field=models.CharField(blank=True, default='', max_length=59),
        ),
        migrations.AddField(
            model_name='profile',
            name='Education',
            field=models.CharField(choices=[('B.TECH', 'B.TECH'), ('M.TECH', 'M.TECH'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('OTHERS', 'OTHERS')], default='Degree', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='Expertise_Subject',
            field=models.CharField(default='', help_text='Ex:JavaScript,Python,English,Algorithms,etc.,', max_length=79),
        ),
        migrations.AddField(
            model_name='profile',
            name='Languages_Spoken',
            field=models.CharField(blank=True, default='English', max_length=39),
        ),
        migrations.AddField(
            model_name='profile',
            name='State',
            field=models.CharField(blank=True, default='', max_length=59),
        ),
        migrations.AddField(
            model_name='profile',
            name='Subjects',
            field=models.CharField(default='', help_text='Ex:various Subjects Your Teach...', max_length=79),
        ),
        migrations.AddField(
            model_name='profile',
            name='Teaching_Experience',
            field=models.TextField(default='GOOD'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Year_Of_Experience',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14')], default='4', max_length=20),
        ),
    ]
