# Generated by Django 3.0 on 2021-01-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210121_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Youtube_Subject',
            field=models.CharField(blank=True, default='', help_text='Ex:JavaScript,Python,English,Algorithms,etc.,', max_length=79),
        ),
        migrations.AddField(
            model_name='profile',
            name='Youtube_Url',
            field=models.CharField(blank=True, default='', help_text='Your Youtube Channel URL', max_length=159),
        ),
    ]
