# Generated by Django 3.0 on 2020-04-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=49)),
                ('Description', models.CharField(max_length=399)),
                ('Location', models.CharField(max_length=49)),
                ('Posted_On', models.DateField()),
                ('In', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=29)),
                ('Duration', models.CharField(choices=[('WEEKS', 'WEEKS'), ('MONTHS', 'MONTHS'), ('YEAR', 'YEAR')], max_length=20)),
            ],
        ),
    ]
