# Generated by Django 3.0 on 2020-05-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Posted_On',
            field=models.DateField(auto_now_add=True),
        ),
    ]
