# Generated by Django 3.0 on 2020-05-01 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20200501_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='Time',
        ),
        migrations.AlterField(
            model_name='projects',
            name='Posted_On',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
