# Generated by Django 3.0 on 2020-05-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20200501_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Linkedin_Profile',
            field=models.CharField(default='', max_length=79),
        ),
    ]
