# Generated by Django 3.0 on 2020-04-29 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=49)),
                ('Email', models.CharField(max_length=59)),
                ('Phone_Number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,15}$')])),
                ('Country', models.CharField(max_length=59)),
                ('State', models.CharField(max_length=59)),
                ('Youtube_Subject', models.CharField(help_text='Which Subject Your Teaching', max_length=79)),
                ('Youtube_Url', models.CharField(help_text='Your Youtube Channel Url', max_length=159)),
            ],
        ),
    ]
