# Generated by Django 3.0 on 2020-04-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorsInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutors',
            name='Name',
        ),
        migrations.AlterField(
            model_name='tutors',
            name='Youtube_Subject',
            field=models.CharField(help_text='What Subject You Are Teaching', max_length=79),
        ),
    ]
