# Generated by Django 3.0 on 2020-04-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorsInfo', '0002_auto_20200429_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='Email',
            field=models.EmailField(max_length=59),
        ),
    ]
