# Generated by Django 3.0 on 2020-04-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorsInfo', '0003_auto_20200429_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='Youtube_Subject',
            field=models.CharField(help_text='Ex:JavaScript,Python,English,Algorithms,etc.,', max_length=79),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='Youtube_Url',
            field=models.CharField(help_text='Your Youtube Channel URL', max_length=159),
        ),
    ]
