# Generated by Django 3.0 on 2020-07-23 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorsInfo', '0004_auto_20200430_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtubers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=59)),
                ('Phone_Number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,15}$')])),
                ('Country', models.CharField(max_length=59)),
                ('State', models.CharField(max_length=59)),
                ('Youtube_Subject', models.CharField(help_text='Ex:JavaScript,Python,English,Algorithms,etc.,', max_length=79)),
                ('Youtube_Url', models.CharField(help_text='Your Youtube Channel URL', max_length=159)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='Youtube_Subject',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='Youtube_Url',
        ),
        migrations.AddField(
            model_name='tutors',
            name='Expertise_Subject',
            field=models.CharField(default='', help_text='Ex:JavaScript,Python,English,Algorithms,etc.,', max_length=79),
        ),
        migrations.AddField(
            model_name='tutors',
            name='Subjects',
            field=models.CharField(default='', help_text='Ex:various Subjects Your Teach...', max_length=79),
        ),
    ]
