# Generated by Django 3.0 on 2021-01-20 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TutorsInfo', '0005_auto_20200723_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors',
            name='Certified_In',
            field=models.CharField(blank=True, default='', help_text='You Can Add Your Certifications Here..', max_length=39),
        ),
        migrations.AddField(
            model_name='tutors',
            name='Education',
            field=models.CharField(choices=[('B.TECH', 'B.TECH'), ('M.TECH', 'M.TECH'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('OTHERS', 'OTHERS')], default='Degree', max_length=30),
        ),
        migrations.AddField(
            model_name='tutors',
            name='Languages_Spoken',
            field=models.CharField(blank=True, default='English', max_length=39),
        ),
        migrations.AddField(
            model_name='tutors',
            name='Teaching_Experience',
            field=models.TextField(default='GOOD'),
        ),
        migrations.AddField(
            model_name='tutors',
            name='Year_Of_Experience',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14')], default='4', max_length=20),
        ),
        migrations.AddField(
            model_name='tutors',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
